###########################
# !Mandatory parameters!: #
###########################

# Directory for all the files 
DIRECTORY: ""
# Your bot token, acquired through @BotFather
TOKEN: ""

# API id and hash required for Pyrogram launch, taken from my.telegram.org
API_ID: ""
API_HASH: ""

# Channel IDs, where MAIN_CHAT_ID is your main channel,
# where all the final posts will be made
# Consider inputting integer format id
MAIN_CHAT_ID: 

# Admin ids, used for reporting errors. At least 1 id is needed
ADMINS:
  - ""


#########################
# All of the parameters below are optional,
# but are recommended to be configured.
# Default values are provided.
#########################
results_dir: "tmp/"
queue_name: "queue.db"
create_logs: True
downloader_logfile: "downloader-log.txt"
server_linux_logfile: "server_linux-log.txt"
# Currently, telegram bots have a 20 MB upload limitation
# for new files. If skip_if_over_20mb is False, 
# the bot will send the admins a message and you will
# have to upload the audio file manually to the temporary 
# channel. Then, the bot will parse that message and continue 
# as usual. If skip_if_over_20mb is True, the bot will 
# delete the folder and remove the link from the queue.
skip_if_over_20mb: True
