###########################
# !Mandatory parameters!: #
###########################

# Directory for all the files 
DIRECTORY: ""
# Your bot token, acquired through @BotFather
TOKEN: ""
# Channel IDs, where MAIN_CHAT_ID is your main channel,
# where all the final posts will be made, and 
# TEMP_CHAT_ID is your temporary channel.
MAIN_CHAT_ID: ""
TEMP_CHAT_ID: ""
# Admin ids, used for reporting errors. At least 1 id is needed
ADMINS:
  - ""


#########################
# All of the parameters below are optional,
# but are recommended to being configured.
# Default values are provided.
#########################
results_dir: "tmp/"
queue_name: "queue.db"
create_logs: 1
downloader_logfile: "downloader-log.txt"
server_linux_logfile: "server_linux-log.txt"

# REGEXES:
re_original_link: "([a-zA-Z0-9_-]{11})(?:\.\.?description)$"
